[project]
name = "voc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.4",
    "pandas>=2.3.3",
    "prefect>=3.6.6",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "streamlit>=1.52.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "uvicorn>=0.38.0",
    "wandb>=0.23.1",
]
