[project]
name = "voc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "polars>=1.37.1",
    "prefect>=3.6.10",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.0",
]
